version: '3.2'
services:
 prometheus:
  image: prom/prometheus:latest
  restart: always
  container_name: prometheus
  ports:
  - 9090:9090
  command:
  - --config.file=/etc/prometheus/prometheus.yml
  volumes:
  - /vagrant_files/prometheus.yml:/etc/prometheus/prometheus.yml:ro


 grafana:
  image: grafana/grafana:latest
  restart: always
  container_name: grafana
  volumes:
   - /vagrant_files/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources/
   - /vagrant_files/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
   - /vagrant_files/grafana/provisioning/grafana.ini:/etc/grafana/grafana.ini
  ports:
   - 3000:3000
  links:
   - prometheus