#global config
global:
 scrape_interval: 15s
 evaluation_interval: 5s
 scrape_timeout: 10s
 external_labels:
  monitor: 'prom'
scrape_configs:
 - job_name: node
   scrape_interval: 5s
   static_configs:
    - targets: ['ubuntu2004:9100']